import type { Metadata } from 'next';
import { locales } from '@/i18nconfig';
import { unstable_setRequestLocale } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { NextIntlClientProvider } from 'next-intl';
import { Locale } from '../types';
import NavBar from '../_components/NavBar';
import Footer from '../_components/Footer';
import '@vercel/examples-ui/globals.css';

import '../globals.css';

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: Locale };
}) {
  const dir = 'ltr';

  if (locales.includes(locale) === false) {
    return notFound();
  }

  unstable_setRequestLocale(locale);
  let messages;
  try {
    messages = (await import(`../_translations/${locale}.json`)).default;
  } catch (error) {
    console.error('Failed to load messages:', error);
    notFound();
  }
  return (
    <html lang={locale} dir={dir}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <NavBar lang={locale} />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
